; Socket constants
  AF_INET         = 2
  SOCK_RAW        = 3
  IPPROTO_ICMP    = 1
  SOCK_STREAM     = 1
  IPPROTO_TCP     = 6
  INVALID_SOCKET  = -1
  SOMAXCONN       = 0x7fffffff
  SOCKADDR_SIZE   = 16
  SOL_SOCKET      = 0xFFFF
  SO_REUSEADDR   = 0x0004
  PORT_NUM       = 7123    ; Define our listening port
  
  ENABLE_ECHO_INPUT = 0x0004
  ENABLE_LINE_INPUT = 0x0002
  ENABLE_PROCESSED_INPUT = 0x0001
  WH_KEYBOARD_LL = 0x13
  WH_MOUSE_LL = 0x14
  PAGE_EXECUTE_READWRITE = 0x40
  ProcessBasicInformation = 0